### ISSUE TITLE
Update the "Link Copied" text

### ISSUE THREAD

**Issue by caffodian** [PolicyStat/ckeditor-plugin-autoid-headings#33]
A customer was confused because they didn't realize the link was to the specific section, so they didn't understand the purpose of the links inserted into the document.

**Comment by caffodian** [comment]
ideas:  

"Link to this section/heading has been copied to your clipboard"
"Section/Heading link has been copied"

**Comment by jms21852** [comment]
More succinct:

Direct link to this section copied
